resources:
- ../../base

#patches:
# - path: replicas.yaml

patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: mywebapp
      spec:
        replicas: 3

configMapGenerator:
- name: mykustom-map
  env: config.properties
